# Generated by Django 2.0 on 2018-03-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
